### ISSUE TITLE
第二步就报错了。

### ISSUE THREAD

**Issue by tackoolin** [Morizeyao/Decoders-Chinese-TF2.0#15]
Traceback (most recent call last):
  File "F:\Decoders-Chinese-TF2.0-master\train_gpt2_keras.py", line 4, in <module>
    import modeling_gpt2
  File "F:\Decoders-Chinese-TF2.0-master\modeling_gpt2.py", line 34, in <module>
    from transformers.configuration_gpt2 import GPT2Config
ModuleNotFoundError: No module named 'transformers.configuration_gpt2'

**Comment by huaminglee** [comment]
我这也同样报这个错，你解决没有？我还没详细读代码
