### ISSUE TITLE
按照流程走了一遍，生成的并没有什么逻辑，请问哪里出现了问题？

### ISSUE THREAD

**Issue by bluesheepcj** [Morizeyao/Decoders-Chinese-TF2.0#3]
2019-12-25 08:12:32.800903: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
 98%|█████████▊| 49/50 [00:17<00:00,  2.22it/s]丨20112011201120112011201120112011201120112011201120112011201120112011201120112011201120112011201120112011足以201120112011201120112011201112201120112011201120112011201120112011201120112011足以2011足以
100%|██████████| 50/50 [00:18<00:00,  2.73it/s]
100%|██████████| 50/50 [00:18<00:00,  2.68it/s]
  0%|          | 0/50 [00:00<?, ?it/s]丨20112011足以201120112011201120112011201120112011足以2011201120112011201120112011201120112011201120112011201120112011201120112011足以2011201120112011201120112011201112去20112011去2011201120112011
 98%|█████████▊| 49/50 [00:18<00:00,  2.22it/s]丨201120112011201120112011201120112011201120112011足以201120112011足以2011足以20112011201120112011201120112011201120112011足以201120112011201120112011足以20112011去201120112011足以201120112011201112
100%|██████████| 50/50 [00:18<00:00,  2.65it/s]
 98%|█████████▊| 49/50 [00:17<00:00,  2.25it/s]丨201120112011201120112011201120112011去20112011足以201120112011去201120112011201120112011201120112011201120112011201120112011足以去201120112011201112201120112011201120112011去2011201120112011
100%|██████████| 50/50 [00:18<00:00,  2.71it/s]

**Comment by Chunshan-Theta** [comment]
發生一樣的問題
args:
Namespace(device='0', length=50, model_config='configs/gpt2/model_config_small.json', model_path='model/', n_ctx=512, prefix='亚洲', repetition_penalty=1.1, spm_model_path='spm_model/ch.model', temperature=1, topk=5, topp=0.95)
2020-01-01 06:55:20.116150: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2020-01-01 06:55:20.231458: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-01 06:55:20.234001: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.234565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
2020-01-01 06:55:20.234819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-01 06:55:20.236136: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-01 06:55:20.237534: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-01-01 06:55:20.237894: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-01-01 06:55:20.239478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-01-01 06:55:20.240704: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-01-01 06:55:20.244547: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-01 06:55:20.244653: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.245273: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.245815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-01-01 06:55:20.246141: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-01-01 06:55:20.251165: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000165000 Hz
2020-01-01 06:55:20.251344: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ecf2c0 executing computations on platform Host. Devices:
2020-01-01 06:55:20.251371: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-01-01 06:55:20.340199: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.340838: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ecf100 executing computations on platform CUDA. Devices:
2020-01-01 06:55:20.340867: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-01-01 06:55:20.341038: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.341530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
2020-01-01 06:55:20.341608: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-01 06:55:20.341625: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-01-01 06:55:20.341638: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-01-01 06:55:20.341651: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-01-01 06:55:20.341663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-01-01 06:55:20.341677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-01-01 06:55:20.341691: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-01-01 06:55:20.341741: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.342268: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.342738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-01-01 06:55:20.342794: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-01-01 06:55:20.343898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-01 06:55:20.343926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-01-01 06:55:20.343936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-01-01 06:55:20.344066: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.344697: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-01-01 06:55:20.345289: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-01-01 06:55:20.345340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14974 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
2020-01-01 06:55:21.056953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
100% 50/50 [00:05<00:00,  9.31it/s]
亚洲李00李以使李0赛季赛季赛季0以0以00以使以赛季李赛季0以使李0使以使使李赛季李0以以使以使赛季00以以0赛季以0
100% 50/50 [00:05<00:00,  9.00it/s]
亚洲李0使00赛季使00以0使0赛季使以赛季李00使0000李李李使使以使0赛季0以0赛季以00以使赛季赛季0李0以0
100% 50/50 [00:05<00:00,  9.11it/s]
亚洲0以赛季以赛季以使赛季以0李以00李李使00使李李以0使0李使赛季赛季00以000使以0赛季0李使赛季使以李以0使
100% 50/50 [00:05<00:00,  9.36it/s]
亚洲000赛季以赛季0使以00使赛季00以以000李0以使李赛季以0李以以李0李0以0以0以0李赛季以00以0以赛季
100% 50/50 [00:05<00:00,  9.59it/s]
亚洲赛季0赛季李以使李0以00使赛季使00使以赛季赛季赛季李0赛季赛季以0以以0以李使以000000使使李使0李使0使李
100% 50/50 [00:05<00:00,  9.01it/s]
亚洲0李赛季以0李0使李0使0李0李000李赛季使使0李0以0使0赛季李李以00李0使以以李使0赛季赛季以00李0
100% 50/50 [00:05<00:00,  9.35it/s]
亚洲00赛季00李00以李0赛季0赛季赛季使李赛季0使0赛季以赛季赛季赛季以以使00以李0赛季李以使使赛季李00以李00以0赛季
100% 50/50 [00:05<00:00,  9.37it/s]
亚洲00李以赛季以以李赛季00赛季使李赛季李以0李使000使李0以0使00赛季0使0000使赛季使00赛季以0以赛季赛季以
100% 50/50 [00:05<00:00,  9.27it/s]
亚洲赛季使0以以使使李赛季使李赛季0赛季使00李李0000以以0使使李0以李0赛季李0以000李李使以00以李李以
100% 50/50 [00:05<00:00,  9.35it/s]
亚洲以使0李00赛季以李李使使0李李李李李0以0以0以0使赛季以使赛季李李使使李使0赛季以使00使使0以000使
100% 50/50 [00:05<00:00,  9.12it/s]
亚洲00以赛季使000李使李000李00赛季0李0赛季0李0李0赛季赛季0李00以0李以李赛季以0李0以0使以0以以
100% 50/50 [00:05<00:00,  8.91it/s]
亚洲使0以0以00李0李以以李赛季李00以使赛季李以赛季以以00赛季使0李以000赛季使使0使000赛季以00李0赛季
[colab](https://colab.research.google.com/drive/1RAEjwAkklmoYV4OI4kMrr7Rj7v6H5DxU#forceEdit=true&sandboxMode=true)

**Comment by Morizeyao** [comment]
你好，欢迎关注本项目！方便联系一下我的微信duzeyao吗？

**Comment by BeanSprouts** [comment]
执行训练，出错：
python train_gpt2_keras.py  --n_ctx 512  --model_config configs/gpt2/model_config_small.json  --pretrained_model ''  --batch_size 1  --tfrecord_path data/tokenized/tokenized.tfrecord  --lr 2e-4  --epochs 10   --steps_per_epoch 100  --output_dir model

错误信息如下：
starting training
Traceback (most recent call last):
  File "C:\Users\shenx\gpt2_gpu\lib\site-packages\transformers\configuration_utils.py", line 225, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_gpt2_keras.py", line 90, in <module>
    main()
  File "train_gpt2_keras.py", line 72, in main
    model = modeling_gpt2.TFGPT2LMHeadModel.from_pretrained(args.pretrained_model)
  File "C:\Users\shenx\gpt2_gpu\lib\site-packages\transformers\modeling_tf_utils.py", line 279, in from_pretrained
    **kwargs,
  File "C:\Users\shenx\gpt2_gpu\lib\site-packages\transformers\configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\shenx\gpt2_gpu\lib\site-packages\transformers\configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
OSError: Model name '''' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/''/config.json' was a path, a m
odel identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or ur
l.

**Comment by huqi66** [comment]
我也遇到同样的问题呢，有解决了的人吗？我就是重复出现“寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托寄托”

**Comment by old-wang-95** [comment]
用`train_gpt2_keras.py`训练出的模型会有这个问题，你用`train_gpt2.py`训练出来的没有这个问题。
