### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u4e28' in position 132

### ISSUE THREAD

**Issue by yangboz** [Morizeyao/Decoders-Chinese-TF2.0#7]
按照流程train结束后，执行bash generate_gpt2_keras.sh 错误信息如下：

2021-01-15 16:28:57.869405: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "generate_gpt2_keras.py", line 102, in <module>
    main()
  File "generate_gpt2_keras.py", line 81, in main
    print('args:\n' + args.__repr__())
UnicodeEncodeError: 'ascii' codec can't encode character '\u4e28' in position 132: ordinal not in range(128)

字符串的问题，有可以参考的语料吗？
谢谢！

**Comment by yangboz** [comment]
export PYTHONIOENCODING=utf8；之后再执行可以开始吐字了。
![Uploading image.png…]()
